ActionList and NavList components (#1268)

diff --git a/script/dev b/script/dev
--- a/script/dev
+++ b/script/dev
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! command -v overmind &> /dev/null
+then
+  echo "Please install overmind."
+fi
+
 # Gems
 bundle install --path vendor/bundle
 yarn install
@@ -15,4 +20,27 @@ pushd docs
 yarn install
 popd
 
-exec overmind start
+while [[ "$#" > 0 ]]; do case $1 in
+  -d|--debug) debug="1"; shift;;
+esac; done
+
+if [ -n "$debug" ]; then
+  mkdir -p tmp/pids
+  overmind start --processes doctocat,assets > tmp/lookbook.log 2>&1 &
+  echo $! > tmp/pids/lookbook.pid
+
+  # ensure we cleanup tmp files and overmind
+  function cleanup {
+    echo "Shutting down..."
+    kill $(cat tmp/pids/lookbook.pid) &>/dev/null
+    rm -f tmp/pids/lookbook.pid tmp/lookbook.log .overmind.sock /tmp/overmind.sock
+  }
+
+  trap cleanup EXIT
+
+  pushd demo
+  bin/rails server -p 4000
+else
+  exec overmind start "$@"
+fi
+
