build(release): exit early if changes need pulling

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -4,8 +4,13 @@ fetch() {
   git fetch --all
 }
 
+remote_history_is_clean() {
+  history =$(git rev-list --count --left-only @{u}...HEAD)
+  [ "$history" == "0" ]
+}
+
 tag_exists_on_remote() {
- git rev-parse --quiet --verify refs/tags/v$1.$2.$3 > /dev/null
+  git rev-parse --quiet --verify refs/tags/v$1.$2.$3 > /dev/null
 }
 
 working_tree_is_clean() {
@@ -85,6 +90,11 @@ main() {
   echo "==================="
 
   fetch
+  if ! remote_history_is_clean; then 
+    echo "Error: changes exist on origin not pulled into this branch. Please pull"
+    exit 1
+  fi 
+
   if ! working_tree_is_clean; then 
     echo "Error: unclean working tree"
     exit 1
