Instead of commenting out the whole workflow, we only execute it on a branch that will never exist

diff --git a/.github/workflows/demo-preview-destroy.yml b/.github/workflows/demo-preview-destroy.yml
--- a/.github/workflows/demo-preview-destroy.yml
+++ b/.github/workflows/demo-preview-destroy.yml
@@ -1,47 +1,46 @@
-#name: Demo Preview Destroy
-#
-#on:
-#  pull_request:
-#    types:
-#      - closed
-#      - locked
-#
-## This allows one deploy workflow to interrupt another
-#concurrency:
-#  group: 'preview-env @ ${{ github.head_ref || github.run_id }} for ${{ github.event.number || github.event.inputs.PR_NUMBER }}'
-#  cancel-in-progress: true
-#
-#jobs:
-#  destory:
-#    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/view_components' && github.actor != 'dependabot[bot]' }}
-#    name: Destroy
-#    runs-on: ubuntu-latest
-#    timeout-minutes: 5
-#    env:
-#      PR_NUMBER: ${{ github.event.number || github.event.inputs.PR_NUMBER }}
-#
-#    steps:
-#      - uses: Azure/login@v1
-#        with:
-#          creds: '{"clientId":"5ad1a188-b944-40eb-a2f8-cc683a6a65a0","clientSecret":"${{ secrets.AZURE_SPN_CLIENT_SECRET }}","subscriptionId":"550eb99d-d0c7-4651-a337-f53fa6520c4f","tenantId":"398a6654-997b-47e9-b12b-9515b896b4de"}'
-#
-#      - name: Check out repo
-#        uses: actions/checkout@v3
-#
-#      - name: Get preview app info
-#        run: ./.github/workflows/demo-preview-app-info.sh
-#
-#      # Succeed despite any non-zero exit code (e.g. if there is no deployment to cancel)
-#      - name: 'Cancel any in progress deployments'
-#        run: |
-#          az deployment group cancel --name ${{ env.DEPLOYMENT_NAME }} -g primer || true
-#      # Delete web app (which will also delete the App Service plan)
-#      # This will succeed even if the app doesn't exist / has already been deleted
-#      - name: 'Delete App Service App (which will also delete the App Service plan)'
-#        run: |
-#          az container delete -n ${{ env.APP_NAME }} -g primer -y &> /dev/null
-#      # Untag all images under this PR's container registry repo - the container registry will automatically remove untagged images.
-#      # This will fail if the IMAGE_REPO doesn't exist, but we don't care
-#      - name: 'Untag all docker images for this PR'
-#        run: |
-#          az acr repository delete -n primer.azurecr.io --repository ${{ env.IMAGE_REPO }} -y || true
+name: Demo Preview Destroy
+
+on:
+  pull_request:
+    branches:
+      - DO_NOT_EXECUTE_THIS_WORKFLOW
+
+# This allows one deploy workflow to interrupt another
+concurrency:
+  group: 'preview-env @ ${{ github.head_ref || github.run_id }} for ${{ github.event.number || github.event.inputs.PR_NUMBER }}'
+  cancel-in-progress: true
+
+jobs:
+  destory:
+    if: ${{ github.event.pull_request.head.repo.full_name == 'primer/view_components' && github.actor != 'dependabot[bot]' }}
+    name: Destroy
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    env:
+      PR_NUMBER: ${{ github.event.number || github.event.inputs.PR_NUMBER }}
+
+    steps:
+      - uses: Azure/login@v1
+        with:
+          creds: '{"clientId":"5ad1a188-b944-40eb-a2f8-cc683a6a65a0","clientSecret":"${{ secrets.AZURE_SPN_CLIENT_SECRET }}","subscriptionId":"550eb99d-d0c7-4651-a337-f53fa6520c4f","tenantId":"398a6654-997b-47e9-b12b-9515b896b4de"}'
+
+      - name: Check out repo
+        uses: actions/checkout@v3
+
+      - name: Get preview app info
+        run: ./.github/workflows/demo-preview-app-info.sh
+
+      # Succeed despite any non-zero exit code (e.g. if there is no deployment to cancel)
+      - name: 'Cancel any in progress deployments'
+        run: |
+          az deployment group cancel --name ${{ env.DEPLOYMENT_NAME }} -g primer || true
+      # Delete web app (which will also delete the App Service plan)
+      # This will succeed even if the app doesn't exist / has already been deleted
+      - name: 'Delete App Service App (which will also delete the App Service plan)'
+        run: |
+          az container delete -n ${{ env.APP_NAME }} -g primer -y &> /dev/null
+      # Untag all images under this PR's container registry repo - the container registry will automatically remove untagged images.
+      # This will fail if the IMAGE_REPO doesn't exist, but we don't care
+      - name: 'Untag all docker images for this PR'
+        run: |
+          az acr repository delete -n primer.azurecr.io --repository ${{ env.IMAGE_REPO }} -y || true
